### PR TITLE
Contributer

### PR DESCRIPTION
**Pull request by mgold1234**

### CODE REVIEW

**Comment by Yarboa** [comment]
@mgold1234 nic work
MHO,  “contribution2.txt” and “contribution3.txt” should reside in the same commit

**Comment by mgold1234** [comment]
do you want me to delete the last commit and combine them?

**Comment by Yarboa** [comment]
> do you want me to delete the last commit and combine them?

Actually it was not a good idea, can you split back for two commits?
Please refer task #5

**Comment by Yarboa** [comment]
Task #6, 
“contribution3.txt” file is not directly related to the “contribution2.txt” and “contribution1.txt” files and therefore should be moved to a different PR.
I hope you understand :)

**Pull request merged**
